### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [expos-model/ExposR#3]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

ExposR has a stronng dependency on 'rgdal', `pgkapi` finds use of `rgdal::readOGR` and `rgdal::setCPLConfigOption` neither declared in NAMESPACE, used in lines 675, 854 (to prime `raster::writeRaster` - terra is the contemorary choice, probably the `gdal=` option to `terra::writeRaster`, and line 1000 (use `terra::vect` and coerce through `raster` methods to your spatial class).

The required fixes are not demanding. Run CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path to detect other uses of retiring packages. Please fix best by June, latest by October 2023 - you were notified last year, so half the available time has elapsed.

**Comment by erboose** [comment]
ExposR version 1.1 imports terra instead of raster and rgdal.
